export const SET_FAVORITES = 'SET_FAVORITES';
export const SET_FAVORITES_FETCHED = 'SET_FAVORITES_FETCHED';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_NEARBY_RESULTS = 'SET_NEARBY_RESULTS';
