export const SET_FAVORITES = 'SET_FAVORITES';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const SET_FAVORITES_FETCHED = 'SET_FAVORITES_FETCHED';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_NEARBY_RESULTS = 'SET_NEARBY_RESULTS';
